Traceback (most recent call last):
  File "e:\dev\wpcc\venv\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "e:\dev\wpcc\venv\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "e:\dev\wpcc\venv\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "e:\dev\wpcc\venv\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\Python39-64\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "e:\dev\wpcc\venv\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "e:\dev\wpcc\venv\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "e:\dev\wpcc\venv\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# %load imports.py
## Local packages:

%matplotlib inline
%load_ext autoreload
%autoreload 2
%config Completer.use_jedi = False  ## (To fix autocomplete)

## External packages:
import pandas as pd
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999
pd.set_option("display.max_columns", None)

import numpy as np
import os

import plotly.express as px 
import plotly.graph_objects as go

import seaborn as sns
import sympy as sp
from sympy.physics.mechanics import (dynamicsymbols, ReferenceFrame,
                                      Particle, Point)
from sympy.physics.vector.printing import vpprint, vlatex
from IPython.display import display, Math, Latex, Markdown
from src.substitute_dynamic_symbols import run, lambdify

import pyro

import sklearn
import pykalman
from statsmodels.sandbox.regression.predstd import wls_prediction_std
import statsmodels.api as sm

from scipy.integrate import solve_ivp

## Local packages:
from src.data import mdl

from src.symbols import *

import src.symbols as symbols
from src import prime_system
from src.models import regression
from src.visualization.regression import show_pred
from src.visualization.plot import track_plot
from src.equation import Equation

## Load models:
# (Uncomment these for faster loading):
import src.models.vmm_nonlinear_EOM  as vmm 

import matplotlib.pyplot as plt
if os.name == 'nt':
    plt.style.use('book.mplstyle')  # Windows
    
## Examples
from example_1 import ship_parameters, df_parameters
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-2-18df5b647127>[0m in [0;36m<module>[1;34m[0m
[0;32m     46[0m [1;32mfrom[0m [0msrc[0m[1;33m.[0m[0mvisualization[0m[1;33m.[0m[0mregression[0m [1;32mimport[0m [0mshow_pred[0m[1;33m[0m[1;33m[0m[0m
[0;32m     47[0m [1;32mfrom[0m [0msrc[0m[1;33m.[0m[0mvisualization[0m[1;33m.[0m[0mplot[0m [1;32mimport[0m [0mtrack_plot[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 48[1;33m [1;32mfrom[0m [0msrc[0m[1;33m.[0m[0mequation[0m [1;32mimport[0m [0mEquation[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     49[0m [1;33m[0m[0m
[0;32m     50[0m [1;31m## Load models:[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'src.equation'
ModuleNotFoundError: No module named 'src.equation'

